### ISSUE TITLE
Error should appear if you have already applied for a job!

### ISSUE THREAD

**Issue by alissm11** [nickclaw/scaffold#63]
I can apply multiple times to the same job. We want an error to show up saying "You have already applied to this job. Please wait until you have been notified from the employer about your application status." Something like that?

**Comment by nickclaw** [comment]
Are you sure? There should be an error..

**Comment by alissm11** [comment]
I got an error.. just a little slow to render. But I think this should be okay. I originally thought the error should be when you first click "apply" - it should take you to the next page to fill in the "blurb"  and then click apply - this is where the error shows up
